import { test, expect } from '@playwright/test';
test('real Wasm UI: navigation, failures, recovery, pause and fresh reset', async ({ page }, info) => {
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  let wasmLoaded = false;
  page.on('response', response => { if (response.url().endsWith('.wasm') && response.ok()) wasmLoaded = true; });
  await page.goto('./');
  await page.getByRole('button', {name:'Start demo', exact:true}).click();
  await expect(page.locator('#status')).toHaveText('Running · Wasm');
  expect(wasmLoaded).toBeTruthy();
  const terminal = page.locator('#terminal');
  await expect(terminal).toContainText('All Targets Latency Overlay');
  await expect(terminal).toContainText('Gateway');
  expect(await terminal.locator('span').evaluateAll(spans => new Set(spans.map(span => getComputedStyle(span).color)).size)).toBeGreaterThan(4);
  await page.getByRole('button', {name:'Pause', exact:true}).click();
  const count = await page.locator('#sample-count').textContent();
  await page.waitForTimeout(1200);
  await expect(page.locator('#sample-count')).toHaveText(count);
  await page.getByRole('button', {name:'API outage', exact:true}).click();
  await page.getByRole('button', {name:'P / Plot', exact:true}).click();
  await page.getByRole('button', {name:'P / Plot', exact:true}).click();
  await expect(terminal).toContainText('Host unreachable');
  await expect(terminal).toContainText('Recent Failures');
  for (let i = 0; i < 3; i++) await page.getByRole('button', {name:'→ Next', exact:true}).click();
  await expect(terminal).toContainText('Target: API');
  await expect(terminal).toContainText('Success:');
  await expect(terminal).toContainText('Failures for API');
  await page.screenshot({path:info.outputPath('failures.png')});
  await terminal.press('ArrowLeft');
  await expect(terminal).toContainText('Target: DNS');
  await terminal.press('p');
  await expect(terminal).toContainText('Ping Latency (ms)');
  await page.getByRole('button', {name:'Healthy network', exact:true}).click();
  await terminal.press(' ');
  await expect(page.locator('#status')).toHaveText('Running · Wasm');
  await page.getByRole('button', {name:'Reset', exact:true}).click();
  await expect(terminal).toContainText('All Targets Latency Overlay');
  await expect(page.locator('[data-scenario="0"]')).toHaveAttribute('aria-pressed', 'true');
  await expect(page.locator('#sample-count')).toHaveText('60 samples');
  await page.screenshot({path:info.outputPath('overview.png')});
  expect(errors).toEqual([]);
});
test('mobile viewport contains page; terminal scrolls and controls work', async ({page}, info) => {
  await page.setViewportSize({width:390, height:844});
  await page.goto('./');
  await page.getByRole('button', {name:'Start demo', exact:true}).click();
  await expect(page.locator('#status')).toHaveText('Running · Wasm');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await page.getByRole('button', {name:'Latency & packet loss', exact:true}).click();
  await page.getByRole('button', {name:'P / Plot', exact:true}).click();
  await page.getByRole('button', {name:'P / Plot', exact:true}).click();
  await expect(page.locator('#terminal')).toContainText('Request timeout');
  await page.screenshot({path:info.outputPath('mobile.png'), fullPage:true});
});
test('failed Wasm download offers a working retry', async ({page}) => {
  await page.route('**/*.wasm', route => route.abort());
  await page.goto('./');
  await page.getByRole('button', {name:'Start demo', exact:true}).click();
  await expect(page.getByRole('button', {name:'Retry', exact:true})).toBeEnabled();
  await page.unroute('**/*.wasm');
  await page.getByRole('button', {name:'Retry', exact:true}).click();
  await expect(page.locator('#status')).toHaveText('Running · Wasm');
});
